name: "Prebid Code Scanner"
description: "Scan code for suspect patterns submitted by Prebid member companies"
branding:
  icon: "check-circle"
  color: "yellow"
inputs:
  token:
    description: Github token
    required: true
  patterns:
    description: Glob patterns to scan, comma-separated
    required: false
    default: "**/*"
  ignores:
    description: Glob patterns to ignore, comma-separated
    required: false
    default: ''
  root:
    description: Source root
    required: false
    default: '.'
  pem:
    description: App secret
    required: true
  appId:
    description: App ID
    required: true
  installationId:
    description: App installation Id
    required: true

runs:
  using: "node24"
  main: "dist/index.js"